# Generated by Django 3.0.8 on 2020-07-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecords',
            name='name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
