# Generated by Django 3.0.8 on 2020-07-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps_log', '0003_auto_20200704_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrecord',
            old_name='price',
            new_name='load',
        ),
    ]
