# Generated by Django 3.0.8 on 2020-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps_log', '0004_auto_20200706_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='load',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='CPU load, %'),
        ),
    ]
