# Generated by Django 3.0.5 on 2020-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps_log', '0007_auto_20200707_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='load',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='CPU load'),
        ),
    ]
